### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jbruxaux** [lz398/distAngsd#3]
Hi!

I gave a try to your new software, as it looks really promising for low coverage data. I managed to install it, and it starts running, but I get a segmentation fault...

I want to use the geno option (not the nuc one), I started from bam files and created first bcf for pairs of samples. I tried with vcf instead, same error. I tried with JC and GTR, same error. I tried with or without 2D inference, same error. With or without multi-threading, same error... I also tried to increase the memory, but it doesn't look like it's the problem.

Here is my script:
```
bcftools mpileup -Ou -d 1000 -f /work/jbruxaux/ref/nucleaire/reference_Prum_Mc_Pterocles.fasta $file1 $file2 -o /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}_tmp.bcf;
bcftools filter -Ou -e INFO/INDEL!=0 /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}_tmp.bcf -o /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.bcf;
bcftools index /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.bcf;
/work/jbruxaux/distAngsd/distAngsd -vcf /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.bcf -o /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.log -method geno -model GTR -outglf /work/jbruxaux/genomic_data/columbidae/nuclear/ -is2Dinfer 1 -isthreading 0 -par 2.0431,0.0821,0,0.0670,0,0.2184,0.2606,0.3265,0.1946 ;

```

Here is the corresponding log file I get from the cluster (the log file from distAngsd is empty):
```
[mpileup] 2 samples in 2 input files
[mpileup] maximum number of reads per input file set to -d 1000
        -> readbcfvcf seek:(null)
        -> Done with preliminary parsing of file: we have data for 1 out of 1 reference sequences
        -> Setting iterator to: reference_Prum_Mc_Pterocles
        -> [file='/work/jbruxaux/genomic_data/columbidae/nuclear/113836_113846.bcf'][chr='reference_Prum_Mc_Pterocles'] Read 710673 records 710673 of which were SNPs. Number of sites used for downstream analysis (MAF >= 0.000000):460275
Done reading everything we have nsites:460275 for samples:2
/var/spool/slurm/d/job35390466/slurm_script: line 150: 52177 Segmentation fault      /work/jbruxaux/distAngsd/distAngsd -vcf /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.bcf -o /work/jbruxaux/genomic_data/columbidae/nuclear/${sp1}_${sp2}.log -method geno -model GTR -outglf /work/jbruxaux/genomic_data/columbidae/nuclear/ -is2Dinfer 1 -isthreading 0 -par 2.0431,0.0821,0,0.0670,0,0.2184,0.2606,0.3265,0.1946

```
It looks like it manages to read the different input files (reference and bcf file), but then it crashes...

And here is the memory usage (I asked on purpose for a lot of memory, just to be on the safe side):
```
Job ID: 35390466
Cluster: genobull
User/Group: jbruxaux/UMR8079
State: FAILED (exit code 139)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:19
CPU Efficiency: 6.25% of 00:05:04 core-walltime
Job Wall-clock time: 00:00:19
Memory Utilized: 62.02 MB
Memory Efficiency: 0.06% of 100.00 GB

```

Any tips on what else I could try? Something obvious that I'm missing? I can give any kind of info.

Thanks in advance!

**Comment by lz398** [comment]
Hi, I've downloaded your file and used the latest distAngsd to run, and there is no fault spotted. I wonder if it has something to do with your local machine or htslib library?

Here is my command: ./distAngsd -vcf ../113836_113846.bcf
Here is the result I got:

Model	Method	Vcf	Threading	Out_uchar	Out_binary
JC	geno	../113836_113846.bcf	0	0	1
	-> readbcfvcf seek:(null)
	-> Done with preliminary parsing of file: we have data for 1 out of 1 reference sequences
	-> Setting iterator to: reference_Prum_Mc_Pterocles
	-> [file='../113836_113846.bcf'][chr='reference_Prum_Mc_Pterocles'] Read 710673 records 710673 of which were SNPs. Number of sites used for downstream analysis (MAF >= 0.000000):460275
Done reading everything we have nsites:460275 for samples:2
vcftest done!
Estimated t = 0.0197926

And it finished in seconds, please let me know if I can help more.

Lei

**Comment by jbruxaux** [comment]
Hi Lei,

Thanks a lot! I will try to check exactly which htslib version I have, and update it if necessary. Glad it worked without any problem, because it looks really promising!
